repository: peterbuga/peterbuga.github.io
favicon: images/favicon.ico

version: 2

name: Petrișor Buga
title: Senior Software Engineer
email: petrisor.buga@gmail.com
email_title: Email
phone: +40 723 375 885
phone_title: Phone
website: https://peterbuga.github.io
website_title: CV

darkmode: false

github_username:  peterbuga
tagline: Developer and FOSS enthusiast
description: Developer and FOSS enthusiast

about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  A general positive person, always up for new challenges. Looking forward for an exciting place to work with an engaged team that shares the same goals and vibe and brings new ideas to life.

  I have an open interest to find and help however I can on various FOSS projects.

  MacOS <i class="fa fa-heart"></i>

content:
  - title: Experience
    layout: list
    content:

      - layout: left
        title: QCatalyst (QC)
        sub_title: Senior Software Developer / DevOps
        caption: '[October 2021] – [present]<br><i class="fa fa-map-marker"></i> Bucharest / Cluj-Napoca'
        link: https://www.qcatalyst.com
        quote: >
          External IT Services company
        description: |
          Continue the practices learned @Virail, developing & monitoring projects for NationalGeographic.org / FiscalNote.com using technologies like, mostly (audio/video streams recording, transcribe, identify+diarize speakers) pipelines & data ETL.

          - DataDog / Kibana / SigNoz
          - NodeJS (nextjs/nestjs/gasbtyjs/sanity.io)
          - Python (Django / FastAPI / Flask)
          - AWS devops w/ terraform
          - PostgreSQL/MySQL/Redis(Valkey)
          - SnowFlake
          - Databricks
          - Astronomer/Airflow
          - Docker/K8s

      - layout: left
        title: Virail
        sub_title: Backend Developer / SysOp /Data ETL & Consistency
        caption: '[July 2016] – [September 2021]<br><i class="fa fa-map-marker"></i> Milano / Berlin'
        link: https://www.virail.com
        quote: >
          Consistent data gathering & extraction
        description: |
          Generic backend developer fixing & adding new futures to a travel aggregator website. I was the person in charge with adding and providing the backbone data of this project using various methods (proxies, VPNs, etc) to match each of the partners needs.

          The list of used & known technologies:

          - Operating systems: MacOS / *nix
          - Databases: PostgreSQL / MySQL / Mongo / Redis
          - PHP frameworks: Phalcon / Laravel / Codeigniter / CakePHP (but in the end they’re all almost the same)
          - Python frameworks: Scrapy / HomeAssistant / many others ( + pyenv / virtualenv)
          - Scripting languages: Bash / Applescript
          - Networking: vpns setup (OpenVPN / L2TP / Wireguard) / nginx / apache2 / haproxy / polipo / squid
          - Various other *nix related environment tools, containerization, sysadmin monitor & networking etc
          - Bonus: I embrace regex as a solution in developing / scripting problems

      - layout: left
        title: Freelancer
        sub_title: UpWork
        caption: '[June 2014] – [June 2016]<br><i class="fa fa-map-marker"></i> Bucharest'
        # link:
        quote: Freelancing
        description: |
          Slowly kickstarting the work on the soon-to-be current job @Virail (as the project was quite small back then) + on the side using the current UpWork platform to take jobs 90% based on scraping data using Scrapy python framework (additionally building quick frontends too visualize this data Bootstrap/Laravel/etc the usual tools)

      - layout: left
        title: AlphaFounders
        sub_title: Backend PHP Developer & Frontend
        caption: '[November 2013] – [May 2014]<br><i class="fa fa-map-marker"></i> Bangkok'
        link: https://rabbitcare.com/
        # quote:
        description: |
          PHP backend developer (+frontend at times) developing a custom CRM/Sales system for aggregated car insurance policies with a working call center on-site & supervising deployments on an AWS cloud infrastructure (called *askhanuman.co.th* back then now it migrated to *rabbitcare.com*)

      - layout: left
        title: TheWorkshop
        sub_title: PHP Developer & Server management
        caption: '[August 2011] – [October 2013]<br><i class="fa fa-map-marker"></i> Bucharest'
        # link:
        quote: Bespoke websites and services
        description: |
          Developing websites (server management & configuration), using the requests and technologies provided by the client. (e.g. small presentation sites, adding new features to old websites, themes/plugins for wordpress, custom CRMs etc)

      - layout: left
        title: DOMAIN MANAGEMENT
        sub_title: SEO Integration & Development
        caption: '[November 2010] – [August 2011]<br><i class="fa fa-map-marker"></i> Bucharest'
        # link:
        # quote:
        description: |
          Developing, customizing and maintaining websites: code, content, SEO integration, SEO marketing.

      - layout: left
        title: CONNSYS
        sub_title: IT Helpdesk & Maintenance
        caption: '[February 2010] – [October 2010]<br><i class="fa fa-map-marker"></i> Bucharest'
        link: https://www.connsys.ro/
        quote: >
          IT & Security externalization services
        description: |
          Maintaining a proper software/hardware work on desktop units, internal network, printers, phone system, administrating the servers & backup.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Highschool
        sub_title: Mathematics & Informatics (National College "Matei Basarab", Bucharest)
        caption: 2003 – 2007
        # quote:
        # description:

      - layout: top-middle
        title: Bachelor
        sub_title: Informatics and Mathematics (Bucharest University Informatics and Mathematics)
        caption: 2007 – 2010
        # quote:
        # description:

      - layout: top-middle
        title: Masters
        sub_title: Mathematics (Bucharest University Informatics and Mathematics)
        caption: 2010 – 2013
        # quote:
        # description:

  - title: A Little More About Me & Hobbies
    layout: text
    content: |
      - Languages: **Romanian** (mother language), **English** (very good), **Italian** (conversation level,
      writing has room for improvement), **French** (1-way conversation mostly, can read / listen),
      **Spanish** (can read / listen). bonus: Thai (I can count & say *Hi!*)

      - Huge fan of any outdoor sports.

      - I have the knowledge / experience to fix almost anything (be it electronic devices or simple
      things like bicycles) and also develop personal projects.

      - … and from time to time I do some gray-hat hacking if the weather keeps me inside.

footer_show_references: true
references_title: powered by <a href="https://github.com/sproogen/modern-resume-theme" target="_blank">sproogen</a>

remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
